### ISSUE TITLE
Invisible `blockquote::before`

### ISSUE THREAD

**Issue by liolok** [jakewies/hugo-theme-codex#114]
The semi-transparent double quotes get invisible randomly, I have to comment out this line in `themes/hugo-theme-codex/assets/scss/partials/_reset.scss`:

```css
html,
body {
  // background-color: $white;
  color: $black;
  height: 100%;
}
```

to make the quotes work as expected, however I have no idea about the side effect.
