### ISSUE TITLE
How to change the order of "section menu"

### ISSUE THREAD

**Issue by casperwang** [jakewies/hugo-theme-codex#142]
Hello~
I've created three "section menu" which is "About", "Archive" and "Home". And I want "Home" to stay at the top, what can I do to change the order of them? Thks

**Comment by rbnis** [comment]
I don't know if it's relevatn to you, but for future reference you can use the `weight` parameter. Like this:

```toml
 [[menu.main]]
  identifier = "home"
  name = home"
  url = "/"
  weight = 10

[[menu.main]]
  identifier = "about"
  name = "about"
  url = "/about/"
  weight = 20

[[menu.main]]
  identifier = "archive"
  name = "archive"
  url = "/archive/"
  weight = 30
```
